import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Controle de EPI Maxiplast",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full bg-black text-white flex flex-row gap-2 px-4 py-2 text-sm font-semibold">
          <Link href="/" className="px-3 py-1 hover:underline">Creme Proteção</Link>
          <span className="mx-1">|</span>
          <Link href="/protetor-auditivo" className="px-3 py-1 hover:underline">Protetor Auditivo</Link>
          <span className="mx-1">|</span>
          <Link href="/cartucho" className="px-3 py-1 hover:underline">Cartucho para Máscara</Link>
          <span className="mx-1">|</span>
        </nav>
        {children}
      </body>
    </html>
  );
}
